replicaCount: 2

image:
  repository: nginx
  tag: "1.21.6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  type_np: NodePort
  type_lb: LoadBalancer
  port: 80

ingress:
  enabled: enable
  className: ""
  host: "my-app.local"
  path: "/"
  tls: false

configMap:
  indexHTML: |
    <html>
    <head>
      <title>Welcome to Nginx</title>
    </head>
    <body>
      <h1>Hello from ConfigMap!</h1>
      <p>This page is served by Nginx using ConfigMap.</p>
    </body>
    </html>
