apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: example-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-secret
                  key: password
          livenessProbe:
            httpGet:
              path: .
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: .
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: .
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
      volumes:
        - name: html
          configMap:
            name: {{ .Release.Name }}-config
