apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  username: bXlfdXNlcm5hbWU=  # Закодированное значение "my_username"
  password: bXlfcGFzc3dvcmQ=  # Закодированное значение "my_password"
